"use client";

import React from "react";
import { Icon } from "@iconify/react";
import { Card } from "@/components/charts/molecules/Card";
import { Button } from "@/components/charts/atoms/Button";
import { Chip } from "@/components/charts/atoms/Chip";
import { Indicator } from "@/components/charts/atoms/Indicator";
import Link from "next/link";

const QUIZZES_DATA = [
  {
    id: "react-core-eval",
    title: "React Core Architecture Quiz",
    jobRole: "Senior React & Next.js Engineer",
    company: "ViteTech Solutions",
    questionsCount: 5,
    durationMinutes: 10,
    status: "pending",
    note: null,
  },
  {
    id: "graphql-systems",
    title: "GraphQL Schema Design & Sync",
    jobRole: "Lead Frontend Systems Engineer",
    company: "CognitiveAI Systems",
    questionsCount: 10,
    durationMinutes: 15,
    status: "passed",
    note: "90%",
  },
  {
    id: "typescript-advanced",
    title: "TypeScript Utility Types & Interfaces",
    jobRole: "Lead Frontend Systems Engineer",
    company: "CognitiveAI Systems",
    questionsCount: 5,
    durationMinutes: 8,
    status: "passed",
    note: "100%",
  },
];

export default function CandidateQuizzes() {
  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8">
      {/* Title */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Skills Assessments (AI Quizzes)</h1>
        <p className="text-sm text-default-500">Complete technical evaluations automatically generated by generative AI models tailored to job requirements.</p>
      </div>

      {/* Main List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {QUIZZES_DATA.map((quiz) => (
          <Card key={quiz.id} className={quiz.status === "pending" ? "border-accent/20" : ""}>
            <Card.Header>
              <div>
                <Card.Title>{quiz.title}</Card.Title>
                <Card.Description>{quiz.jobRole}</Card.Description>
              </div>
              <Icon
                icon={quiz.status === "pending" ? "solar:clipboard-list-bold-duotone" : "solar:verified-check-bold-duotone"}
                className={`text-2xl ${quiz.status === "pending" ? "text-warning animate-pulse" : "text-success"}`}
              />
            </Card.Header>
            <Card.Content className="space-y-4 py-2">
              <div className="flex justify-between items-center text-xs font-semibold text-default-500 border-b border-default-100 dark:border-default-50/10 pb-2">
                <span>Company Sponsor</span>
                <span className="text-default-800 dark:text-default-200">{quiz.company}</span>
              </div>
              <div className="flex justify-between items-center text-xs font-semibold text-default-500 border-b border-default-100 dark:border-default-50/10 pb-2">
                <span>Quiz Details</span>
                <span className="text-default-800 dark:text-default-200">{quiz.questionsCount} Questions • {quiz.durationMinutes} Mins</span>
              </div>
              <div className="flex justify-between items-center text-xs font-semibold text-default-500">
                <span>Evaluation Status</span>
                {quiz.status === "pending" ? (
                  <Chip color="warning" variant="soft">Action Required</Chip>
                ) : (
                  <Chip color="success" variant="soft">Passed ({quiz.note})</Chip>
                )}
              </div>
            </Card.Content>
            <Card.Footer>
              {quiz.status === "pending" ? (
                <Link href={`/candidate/quizzes/${quiz.id}`} className="w-full">
                  <Button
                    startIcon="solar:playback-speed-bold"
                    variant="primary"
                    className="w-full"
                  >
                    Start Quiz (Timer Active)
                  </Button>
                </Link>
              ) : (
                <Button
                  startIcon="solar:document-text-bold"
                  variant="outline"
                  className="w-full"
                  isDisabled
                >
                  Assessment Completed
                </Button>
              )}
            </Card.Footer>
          </Card>
        ))}
      </div>
    </div>
  );
}
