"use client";

import React, { useState, useEffect } from "react";
import { Icon } from "@iconify/react";
import { Card } from "@/components/candidate/Card";
import { Button } from "@/components/candidate/Button";
import { Chip } from "@/components/candidate/Chip";
import Link from "next/link";
import { api } from "@/lib/api";

export default function CandidateQuizzes() {
  const [quizzes, setQuizzes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadQuizzes = async () => {
      try {
        const res: any = await api.get("/api/candidates/quizzes");
        if (res.success && Array.isArray(res.data)) {
          const mapped = res.data.map((q: any) => {
            const hasTaken = q.testResults && q.testResults.length > 0;
            const latestResult = hasTaken ? q.testResults[0] : null;
            
            let status = "pending";
            let note = null;
            if (hasTaken && latestResult) {
              status = latestResult.passed ? "passed" : "failed";
              note = `${latestResult.score}%`;
            }

            return {
              id: q.id,
              title: q.title,
              jobRole: q.jobOffer?.title || "Target Position",
              company: q.jobOffer?.recruiter?.companyName || "Sponsor Company",
              questionsCount: q.questions ? q.questions.length : 5,
              durationMinutes: 10,
              status,
              note
            };
          });
          setQuizzes(mapped);
        }
      } catch (err) {
        console.error("Error loading quizzes:", err);
      } finally {
        setLoading(false);
      }
    };
    loadQuizzes();
  }, []);

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8">
      {/* Title */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Skills Assessments (AI Quizzes)</h1>
        <p className="text-sm text-default-550">Complete technical evaluations automatically generated by generative AI models tailored to job requirements.</p>
      </div>

      {/* Main List */}
      <div className="space-y-6">
        {loading ? (
          <div className="text-center py-24 text-default-450 font-bold">
            <Icon icon="solar:spinner-bold" className="animate-spin text-3xl mx-auto mb-2 text-accent" />
            Loading Quizzes...
          </div>
        ) : quizzes.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {quizzes.map((quiz) => (
              <Card key={quiz.id} className={quiz.status === "pending" ? "border-accent/20" : ""}>
                <Card.Header>
                  <div>
                    <Card.Title>{quiz.title}</Card.Title>
                    <Card.Description>{quiz.jobRole}</Card.Description>
                  </div>
                  <Icon
                    icon={quiz.status === "pending" ? "solar:clipboard-list-bold-duotone" : "solar:verified-check-bold-duotone"}
                    className={`text-2xl ${quiz.status === "pending" ? "text-warning animate-pulse" : "text-success"}`}
                  />
                </Card.Header>
                <Card.Content className="space-y-4 py-2">
                  <div className="flex justify-between items-center text-xs font-semibold text-default-500 border-b border-default-100 dark:border-default-50/10 pb-2">
                    <span>Company Sponsor</span>
                    <span className="text-default-800 dark:text-default-200">{quiz.company}</span>
                  </div>
                  <div className="flex justify-between items-center text-xs font-semibold text-default-500 border-b border-default-100 dark:border-default-50/10 pb-2">
                    <span>Quiz Details</span>
                    <span className="text-default-800 dark:text-default-200">{quiz.questionsCount} Questions • {quiz.durationMinutes} Mins</span>
                  </div>
                  <div className="flex justify-between items-center text-xs font-semibold text-default-500">
                    <span>Evaluation Status</span>
                    {quiz.status === "pending" ? (
                      <Chip color="warning" variant="soft">Action Required</Chip>
                    ) : (
                      <Chip color="success" variant="soft">Passed ({quiz.note})</Chip>
                    )}
                  </div>
                </Card.Content>
                <Card.Footer>
                  {quiz.status === "pending" ? (
                    <Link href={`/candidate/quizzes/${quiz.id}`} className="w-full">
                      <Button
                        startIcon="solar:playback-speed-bold"
                        variant="primary"
                        className="w-full"
                      >
                        Start Quiz (Timer Active)
                      </Button>
                    </Link>
                  ) : (
                    <Button
                      startIcon="solar:document-text-bold"
                      variant="outline"
                      className="w-full"
                      isDisabled
                    >
                      Assessment Completed
                    </Button>
                  )}
                </Card.Footer>
              </Card>
            ))}
          </div>
        ) : (
          <div className="text-center py-16 bg-white dark:bg-[#1f2633] rounded-2xl border border-slate-200/80 dark:border-slate-850 shadow-sm text-default-400">
            <Icon icon="solar:clipboard-remove-broken" className="text-4xl mx-auto mb-3 text-default-300" />
            <p className="font-bold text-sm">No quizzes pending</p>
            <p className="text-xs text-default-500 mt-1">Once you apply to jobs requiring assessments, they will appear here.</p>
          </div>
        )}
      </div>
    </div>
  );
}
